version: '3.8'

services:
  go:
    build: .
    ports:
      - "8181:8181"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: bookinguser
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: booking
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres-db:
